import { Player } from '../models/Player.js';
import { StatusEffect, StatusEffectType } from '../models/StatusEffect.js';
import { StatusAppliedEvent, StatusExpiredEvent, StatusDamageEvent } from '../models/RoundResult.js';
import { GAME_CONSTANTS } from '../constants.js';
import { clamp } from '../../utils/helpers.js';
import { createLogger } from '../../utils/logger.js';

const log = createLogger('StatusSystem');

/**
 * Manages status effect application, ticking, and expiration.
 */
export class StatusSystem {
  /**
   * Processes all status effects for a player at the start of the round.
   * Returns events generated by status ticks (damage over time, healing, etc.).
   */
  tick(player: Player): {
    damageEvents: StatusDamageEvent[];
    expiredEvents: StatusExpiredEvent[];
    totalDamage: number;
    totalHeal: number;
  } {
    const damageEvents: StatusDamageEvent[] = [];
    const expiredEvents: StatusExpiredEvent[] = [];
    let totalDamage = 0;
    let totalHeal = 0;

    const remainingEffects: StatusEffect[] = [];

    for (const effect of player.statusEffects) {
      // Process tick effects
      switch (effect.type) {
        case 'bleeding': {
          const dmg = GAME_CONSTANTS.BLEED_DAMAGE * effect.intensity;
          totalDamage += dmg;
          damageEvents.push({
            type: 'status_damage',
            playerId: player.id,
            statusType: 'bleeding',
            amount: dmg,
          });
          break;
        }
        case 'poisoned': {
          const dmg = GAME_CONSTANTS.POISON_DAMAGE;
          totalDamage += dmg;
          damageEvents.push({
            type: 'status_damage',
            playerId: player.id,
            statusType: 'poisoned',
            amount: dmg,
          });
          break;
        }
        case 'regenerating': {
          const heal = GAME_CONSTANTS.REGEN_HEAL;
          totalHeal += heal;
          break;
        }
      }

      // Decrement duration
      effect.duration--;

      if (effect.duration <= 0) {
        expiredEvents.push({
          type: 'status_expired',
          playerId: player.id,
          statusType: effect.type,
        });
        log.debug(`${player.username}'s ${effect.type} expired`);
      } else {
        remainingEffects.push(effect);
      }
    }

    // Apply damage and healing
    if (totalDamage > 0) {
      player.hp = clamp(player.hp - totalDamage, 0, player.maxHp);
      player.damageReceived += totalDamage;
    }
    if (totalHeal > 0) {
      player.hp = clamp(player.hp + totalHeal, 0, player.maxHp);
    }

    player.statusEffects = remainingEffects;

    return { damageEvents, expiredEvents, totalDamage, totalHeal };
  }

  /**
   * Applies a new status effect to a player.
   */
  apply(
    player: Player,
    type: StatusEffectType,
    duration: number,
    intensity: number = 1,
    sourcePlayerId: string | null = null,
  ): StatusAppliedEvent {
    // Check if the effect already exists
    const existing = player.statusEffects.find(e => e.type === type);

    if (existing) {
      // Refresh duration (take the longer one)
      existing.duration = Math.max(existing.duration, duration);
      // Stack intensity if stackable
      if (type === 'bleeding') {
        existing.intensity += intensity;
      } else {
        existing.intensity = Math.max(existing.intensity, intensity);
      }
    } else {
      player.statusEffects.push({
        type,
        duration,
        intensity,
        sourcePlayerId,
      });
    }

    log.debug(`Applied ${type} (${duration} rounds) to ${player.username}`);
    return {
      type: 'status_applied',
      playerId: player.id,
      statusType: type,
      duration,
      sourcePlayerId,
    };
  }

  /**
   * Removes all instances of a status effect type from a player.
   */
  remove(player: Player, type: StatusEffectType): void {
    player.statusEffects = player.statusEffects.filter(e => e.type !== type);
  }

  /**
   * Clears all temporary round-based effects (defend, hide, move).
   * Called at the start of each round before new actions are processed.
   */
  clearRoundEffects(player: Player): void {
    player.statusEffects = player.statusEffects.filter(
      e => e.type !== 'defended' && e.type !== 'hidden'
    );
    delete player.metadata['moved'];
  }
}
